CREATE TABLE pets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id      BIGINT                                  NOT NULL,
    name          VARCHAR(64)                             NOT NULL,
    species       VARCHAR(32)                             NOT NULL,
    breed         VARCHAR(64),
    date_of_birth date,
    notes         VARCHAR(512),
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     VARCHAR(128)                            NOT NULL,
    username      VARCHAR(64)                             NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(60)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT      NOT NULL,
    roles   VARCHAR(32) NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id);