CREATE TABLE pets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    name       VARCHAR(64)                             NOT NULL,
    species    VARCHAR(32)                             NOT NULL,
    sex        VARCHAR(16),
    breed      VARCHAR(64),
    birth_year INT,
    birth_date date,
    weight     DOUBLE PRECISION,
    notes      VARCHAR(512),
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT      NOT NULL,
    roles   VARCHAR(32) NOT NULL
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     VARCHAR(128)                            NOT NULL,
    username      VARCHAR(64)                             NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(60)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vet_profile_specializations
(
    vet_profile_id BIGINT      NOT NULL,
    specialization VARCHAR(64) NOT NULL
);

CREATE TABLE vet_profiles
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                      BIGINT                                  NOT NULL,
    bio                          VARCHAR(255),
    accepts_new_patients         BOOLEAN                                 NOT NULL,
    average_visit_length_minutes INT                                     NOT NULL,
    CONSTRAINT pk_vet_profiles PRIMARY KEY (id)
);

CREATE TABLE vet_schedule_entries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vet_profile_id      BIGINT                                  NOT NULL,
    day_of_week         VARCHAR(16)                             NOT NULL,
    start_time          time                                    NOT NULL,
    end_time            time                                    NOT NULL,
    slot_length_minutes INT                                     NOT NULL,
    CONSTRAINT pk_vet_schedule_entries PRIMARY KEY (id)
);

CREATE TABLE vet_time_off
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vet_profile_id BIGINT                                  NOT NULL,
    start_date     date                                    NOT NULL,
    end_date       date                                    NOT NULL,
    reason         VARCHAR(255),
    CONSTRAINT pk_vet_time_off PRIMARY KEY (id)
);

CREATE TABLE visits
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id         BIGINT                                  NOT NULL,
    vet_profile_id BIGINT                                  NOT NULL,
    visit_date     date                                    NOT NULL,
    start_time     time                                    NOT NULL,
    end_time       time                                    NOT NULL,
    status         VARCHAR(32)                             NOT NULL,
    reason         VARCHAR(255),
    notes          VARCHAR(1024),
    CONSTRAINT pk_visits PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE vet_profiles
    ADD CONSTRAINT uc_vet_profiles_user UNIQUE (user_id);

CREATE INDEX idx_visits_vet_profile_and_date ON visits (vet_profile_id, visit_date);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE vet_profiles
    ADD CONSTRAINT FK_VET_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE vet_schedule_entries
    ADD CONSTRAINT FK_VET_SCHEDULE_ENTRIES_ON_VET_PROFILE FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);

ALTER TABLE vet_time_off
    ADD CONSTRAINT FK_VET_TIME_OFF_ON_VET_PROFILE FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);

ALTER TABLE visits
    ADD CONSTRAINT FK_VISITS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

CREATE INDEX idx_visits_pet_id ON visits (pet_id);

ALTER TABLE visits
    ADD CONSTRAINT FK_VISITS_ON_VET_PROFILE FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE vet_profile_specializations
    ADD CONSTRAINT fk_vet_profile_specializations_on_vet_profile FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);