CREATE TABLE pets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    name       VARCHAR(64)                             NOT NULL,
    species    VARCHAR(32)                             NOT NULL,
    sex        VARCHAR(16),
    breed      VARCHAR(64),
    birth_year INT,
    birth_date date,
    weight     DOUBLE PRECISION,
    notes      VARCHAR(512),
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT      NOT NULL,
    roles   VARCHAR(32) NOT NULL
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     VARCHAR(128)                            NOT NULL,
    username      VARCHAR(64)                             NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(60)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id);