CREATE TABLE medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id BIGINT NOT NULL,
    vet_profile_id BIGINT NOT NULL,
    visit_id BIGINT NOT NULL,
    title VARCHAR(128),
    diagnosis VARCHAR(1024),
    treatment VARCHAR(1024),
    prescriptions VARCHAR(1024),
    notes VARCHAR(2048),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_medical_records PRIMARY KEY (id),
    CONSTRAINT uk_medical_records_visit_id UNIQUE (visit_id)
);

CREATE INDEX idx_medical_records_pet_id ON medical_records (pet_id);
CREATE INDEX idx_medical_records_vet_profile_id ON medical_records (vet_profile_id);

ALTER TABLE medical_records ADD CONSTRAINT fk_medical_records_pet FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE medical_records ADD CONSTRAINT fk_medical_records_vet_profile FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);
ALTER TABLE medical_records ADD CONSTRAINT fk_medical_records_visit FOREIGN KEY (visit_id) REFERENCES visits (id);

