CREATE TABLE vet_profile_specializations
(
    vet_profile_id BIGINT      NOT NULL,
    specialization VARCHAR(64) NOT NULL
);

CREATE TABLE vet_profiles
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                      BIGINT                                  NOT NULL,
    bio                          VARCHAR(255),
    accepts_new_patients         BOOLEAN                                 NOT NULL,
    average_visit_length_minutes INT                                     NOT NULL,
    CONSTRAINT pk_vet_profiles PRIMARY KEY (id)
);

CREATE TABLE vet_schedule_entries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vet_profile_id      BIGINT                                  NOT NULL,
    day_of_week         VARCHAR(16)                             NOT NULL,
    start_time          time                                    NOT NULL,
    end_time            time                                    NOT NULL,
    slot_length_minutes INT                                     NOT NULL,
    CONSTRAINT pk_vet_schedule_entries PRIMARY KEY (id)
);

CREATE TABLE vet_time_off
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vet_profile_id BIGINT                                  NOT NULL,
    start_date     date                                    NOT NULL,
    end_date       date                                    NOT NULL,
    reason         VARCHAR(255),
    CONSTRAINT pk_vet_time_off PRIMARY KEY (id)
);

ALTER TABLE vet_profiles
    ADD CONSTRAINT uc_vet_profiles_user UNIQUE (user_id);

ALTER TABLE vet_profiles
    ADD CONSTRAINT FK_VET_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE vet_schedule_entries
    ADD CONSTRAINT FK_VET_SCHEDULE_ENTRIES_ON_VET_PROFILE FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);

ALTER TABLE vet_time_off
    ADD CONSTRAINT FK_VET_TIME_OFF_ON_VET_PROFILE FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);

ALTER TABLE vet_profile_specializations
    ADD CONSTRAINT fk_vet_profile_specializations_on_vet_profile FOREIGN KEY (vet_profile_id) REFERENCES vet_profiles (id);